#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: analytics-api
  when: redeploy | default(False) | bool

- name: Deploy analytics-api service
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: True
  vars:
    ANALYTICS_API_DATABASES:
      default:
        ENGINE: 'django.db.backends.mysql'
        NAME: "{{ ANALYTICS_API_DEFAULT_DB_NAME }}"
        USER: "{{ ANALYTICS_MYSQL_USERNAME }}"
        PASSWORD: "{{ ANALYTICS_MYSQL_PASSWORD }}"
        HOST: "{{ ANALYTICS_MYSQL_HOST }}"
        PORT: "{{ ANALYTICS_MYSQL_PORT }}"
      reports:
        ENGINE: 'django.db.backends.mysql'
        NAME: "{{ ANALYTICS_API_REPORTS_DB_NAME }}"
        USER: "{{ ANALYTICS_MYSQL_USERNAME }}"
        PASSWORD: "{{ ANALYTICS_MYSQL_PASSWORD }}"
        HOST: "{{ ANALYTICS_MYSQL_HOST }}"
        PORT: "{{ ANALYTICS_MYSQL_PORT }}"
    ANALYTICS_API_ELASTICSEARCH_CONNECTION_DEFAULT_REGION: 'us-west-1'
    ANALYTICS_API_NGINX_PORT: '80'
    ANALYTICS_API_VERSION: 'rc'
    CLUSTER_NAME: analytics-api
    COMMON_GIT_PATH: 'Stanford-Online'
    COMMON_MYSQL_MIGRATE_PASS: "{{ ANALYTICS_MYSQL_PASSWORD }}"
    COMMON_MYSQL_MIGRATE_USER: "{{ ANALYTICS_MYSQL_USERNAME }}"
    migrate_db: 'yes'
    disable_edx_services: false
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/db.yml"
  roles:
    - aws
    - security
    - mysql
    - edxlocal
    - analytics_api
    - role: nginx
      nginx_sites:
        - analytics_api
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
  tasks:
    - name: 'Install libffi-dev'
      apt: name=libffi-dev state=present
    - name: 'Install make'
      apt: name=make state=present
