#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: insights
  when: redeploy | default(False) | bool

- name: Deploy insights service
  hosts: "tag_Cluster_{{ CLUSTER_NAME }}:&tag_todo_deploy:&tag_Deployment_{{ COMMON_DEPLOYMENT }}:&tag_Number_{{ CLUSTER_NUMBER }}"
  gather_facts: True
  become: True
  vars:
    CLUSTER_NAME: insights
    COMMON_MYSQL_MIGRATE_PASS: "{{ ANALYTICS_MYSQL_PASSWORD }}"
    COMMON_MYSQL_MIGRATE_USER: "{{ ANALYTICS_MYSQL_USERNAME }}"
    INSIGHTS_CMS_BASE: "{{ EDXAPP_LMS_BASE_SCHEME }}://{{ EDXAPP_CMS_BASE }}"
    INSIGHTS_CMS_COURSE_SHORTCUT_BASE_URL: "{{ INSIGHTS_CMS_BASE }}/course"
    INSIGHTS_DATABASE_HOST: "{{ ANALYTICS_MYSQL_HOST }}"
    INSIGHTS_DATABASE_PASSWORD: "{{ ANALYTICS_MYSQL_PASSWORD }}"
    INSIGHTS_DATABASE_PORT: "{{ ANALYTICS_MYSQL_PORT }}"
    INSIGHTS_DATABASE_USER: "{{ ANALYTICS_MYSQL_USERNAME }}"
    INSIGHTS_FEEDBACK_EMAIL: 'courseops@stanfordonline.zendesk.com'
    INSIGHTS_LMS_BASE: "{{ EDXAPP_LMS_BASE_SCHEME }}://{{ EDXAPP_LMS_BASE }}"
    INSIGHTS_LMS_COURSE_SHORTCUT_BASE_URL: "{{ INSIGHTS_LMS_BASE }}/courses"
    INSIGHTS_MKTG_BASE: "{{ INSIGHTS_LMS_BASE }}"
    INSIGHTS_NGINX_PORT: '80'
    INSIGHTS_PRIVACY_POLICY_URL: "{{ INSIGHTS_MKTG_BASE }}/privacy"
    INSIGHTS_TERMS_OF_SERVICE_URL: "{{ INSIGHTS_MKTG_BASE }}/tos"
    INSIGHTS_VERSION: 'rc'
    migrate_db: 'yes'
    disable_edx_services: false
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/db.yml"
  roles:
    - aws
    - security
    - mysql
    - edxlocal
    - role: nginx
      nginx_sites:
        - insights
    - role: insights
      COMMON_GIT_PATH: 'Stanford-Online'
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
  tasks:
    - name: 'Install libffi-dev'
      apt: name=libffi-dev state=present
    - name: 'Install make'
      apt: name=make state=present
