#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: notifier
    CLUSTER_NUMBER: 1
  when: redeploy | default(False) | bool
- name: "Setup {{ CLUSTER_NAME }}"
  hosts:
    - "{{ CLUSTER_NAME }}{{ CLUSTER_NUMBER }}[-1]"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: notifier
    CLUSTER_NUMBER: 1
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
  roles:
    - role: notifier
      tags: notifier
- include: ../playbooks/ami.yml
  when: redeploy | default(False) | bool
