#!/usr/bin/env ansible-playbook
---
#
# When running this playbook you must use '--skip-tags="jenkins-seed-job"'
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_NAME: scheduler
    CLUSTER_NUMBER: 1
  when: redeploy | default(False) | bool

- name: Deploy scheduler service
  hosts:
    - "{{ CLUSTER_NAME }}{{ CLUSTER_NUMBER }}[-1]"
  gather_facts: True
  become: True
  vars:
    CLUSTER_NAME: scheduler
    CLUSTER_NUMBER: 1
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
    - "{{ COMMON_DEPLOYMENT_DIR }}/{{ CLUSTER_NAME }}.yml"
  roles:
    - role: jenkins_analytics
      tags: jenkins_analytics
      role: jenkins_analytics_configs
      tags: jenkins_analytics_configs
- include: ../playbooks/ami.yml
  when: redeploy | default(False) | bool
