---
buildbot_worker_group: 'buildbot_worker'
buildbot_worker_user: 'buildbot_worker'

buildbot_worker_dir: "{{ COMMON_APP_DIR }}/buildbot_worker"
buildbot_worker_venv: "{{ buildbot_worker_dir }}/venv"
buildbot_worker_venv_bin: "{{ buildbot_worker_venv }}/bin"

buildbot_worker_configuration_requirements:
  - 'nodejs'
  - 'python-demjson'

buildbot_worker_edx_platform_requirements:
  - 'bundler'
  - 'gettext'
